name: Recreate Zip File

on:
  workflow_dispatch:

jobs:
  recreate-zip:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create Zip
      run: |
        python3 zip_mapped.py
        zip -r -q binaries.zip binaries

    - name: Commit and push changes
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"

        git add .
        git commit -m "Recreate ZIP file"
        git push